"""empty message

Revision ID: b33f0ca9b864
Revises: 41736432e02c
Create Date: 2023-01-05 14:13:12.958228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33f0ca9b864'
down_revision = '41736432e02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('important',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('important',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
